<?php
declare(strict_types=1);

ini_set('display_errors', '0');

$title = 'PROXTEL Landing Page Starter';
?>
<!doctype html>
<html lang="es-MX">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= htmlspecialchars($title, ENT_QUOTES, 'UTF-8') ?></title>
    <meta name="description" content="Landing page starter generated by PROXTEL AI Agency.">
    <link rel="stylesheet" href="assets/css/app.css">
</head>
<body>
    <main class="hero">
        <p class="eyebrow">PROXTEL AI AGENCY</p>
        <h1><?= htmlspecialchars($title, ENT_QUOTES, 'UTF-8') ?></h1>
        <p>Replace this message with the validated project value proposition.</p>
        <a class="cta" href="#contacto">Continuar</a>
    </main>
    <script src="assets/js/app.js" defer></script>
</body>
</html>