<?php
declare(strict_types=1);

ini_set('display_errors', '0');

$title = 'PROXTEL Website Starter';
$description = 'Starter base generated by PROXTEL AI Agency.';
?>
<!doctype html>
<html lang="es-MX">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= htmlspecialchars($title, ENT_QUOTES, 'UTF-8') ?></title>
    <meta name="description" content="<?= htmlspecialchars($description, ENT_QUOTES, 'UTF-8') ?>">
    <link rel="stylesheet" href="assets/css/app.css">
</head>
<body>
    <main class="shell">
        <p class="eyebrow">PROXTEL AI AGENCY</p>
        <h1><?= htmlspecialchars($title, ENT_QUOTES, 'UTF-8') ?></h1>
        <p><?= htmlspecialchars($description, ENT_QUOTES, 'UTF-8') ?></p>
    </main>
    <script src="assets/js/app.js" defer></script>
</body>
</html>